---
title: "Libreria Srvyr"
author: "Andrea Díaz Sánchez"
date: "2022-09-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
La librería survey, básicamente, permite el análisis de muestras de encuestas complejas. Aunque también se usa en el resumen de estadísticas como la media, el total o el cuantil, los modelos lineales generalizados, las varianzas por linealización de series de Taylor o ponderaciones replicadas, etc.

El paquete survey incorpora partes de la sintaxis de dplyr al análisis de encuestas lo que permitiría calcular estadísticas de resumen de datos de encuestas con diseños complejos.

Para utilizarlo se declara Inicialmente las características técnicas de la encuesta. Una vez el paquete reconoce a la encuesta, se pueden utilizar cualquiera de las técnicas de análisis y modelización que nos proporciona el paquete sin necesidad de re-especificar la parte técnica.

Ejemplos de uso: 
<https://rpubs.com/jaortega/EncuestaR2>
<https://github.com/gergness/srvyr>

Los Autores del paquete survey que fue creado en enero de 2006 fueron:	Greg Freedman Ellis [aut, cre], Thomas Lumley [ctb], Tomasz Żółtak [ctb], Ben Schneider [aut, ctb], Pavel N. Krivitsky

** El principal autor y más reconocido fue Greg Freedman Ellis:** 
<https://www.linkedin.com/in/gdfe>
Educación en la universidad de Northwestern: Licenciatura en Economía y Métodos Matemáticos en Ciencias Sociales 

El cual fue becario de posgrado en Institute for Health Metrics and Evaluation (sept 2011-jul 2014), Seattle. WA. En la actualidad, es desarrollador de R en Crunch.io, encargado del desarrollo de paquetes R que proporcionan una interfaz de secuencias de comandos para el almacén de datos basado en la nube de Crunch.io y el motor analítico diseñado para datos de encuestas.



Referencias:
 <https://mran.microsoft.com/snapshot/2020-04-27/web/packages/srvyr/vignettes/srvyr-vs-survey.html>

  
